# Generated by Django 6.0.7 on 2026-07-27 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ('-created_at', '-id')},
        ),
        migrations.AlterModelOptions(
            name='room',
            options={'ordering': ('-created_at', '-id')},
        ),
        migrations.RemoveIndex(
            model_name='message',
            name='chat_messag_room_id_edc775_idx',
        ),
        migrations.AddField(
            model_name='room',
            name='room_hash',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['room', '-created_at', '-id'], name='chat_messag_room_id_caf393_idx'),
        ),
        migrations.AddConstraint(
            model_name='room',
            constraint=models.UniqueConstraint(condition=models.Q(('room_hash__isnull', False), ('type', 'ONE')), fields=('room_hash',), name='unique_one_to_one_room_hash'),
        ),
    ]
