# Generated by Django 6.0.7 on 2026-07-30 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_alter_user_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='about',
            field=models.CharField(blank=True, default='Hey there! I am using WhatsApp Lite.', max_length=139),
        ),
    ]
