# Generated by Django 6.0.7 on 2026-07-31 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0007_block'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='is_hidden',
            field=models.BooleanField(default=False),
        ),
    ]
