# Generated by Django 6.0.7 on 2026-07-31 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0008_participant_is_hidden'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='block',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='block',
            name='blocked',
        ),
        migrations.RemoveField(
            model_name='block',
            name='blocker',
        ),
        migrations.AlterUniqueTogether(
            name='deletedmessage',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='deletedmessage',
            name='message',
        ),
        migrations.RemoveField(
            model_name='deletedmessage',
            name='user',
        ),
        migrations.RemoveIndex(
            model_name='message',
            name='chat_messag_sender__23ffd3_idx',
        ),
        migrations.RemoveIndex(
            model_name='message',
            name='chat_messag_room_id_caf393_idx',
        ),
        migrations.RemoveIndex(
            model_name='participant',
            name='chat_partic_user_id_2c631f_idx',
        ),
        migrations.RemoveIndex(
            model_name='readreceipt',
            name='chat_readre_user_id_694e84_idx',
        ),
        migrations.RemoveField(
            model_name='user',
            name='avatar',
        ),
        migrations.DeleteModel(
            name='Block',
        ),
        migrations.DeleteModel(
            name='DeletedMessage',
        ),
        migrations.RemoveField(
            model_name='message',
            name='attachment',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='is_hidden',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='is_muted',
        ),
    ]
