# Generated by Django 6.0.7 on 2026-08-01 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0012_deletedmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='is_hidden',
            field=models.BooleanField(default=False),
        ),
    ]
